version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 214094364511.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t fargate-demo:latest .
      - docker tag fargate-demo:latest 214094364511.dkr.ecr.us-east-1.amazonaws.com/fargate-demo:latest
  post_build:
    commands:
      - docker push 214094364511.dkr.ecr.us-east-1.amazonaws.com/fargate-demo:latest
      - printf '[{"name":helloWorld,"imageUri":"%s"}]' 214094364511.dkr.ecr.us-east-1.amazonaws.com/fargate-demo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
